### ISSUE TITLE
Fault message "Invalid type"

### ISSUE THREAD

**Issue by basementmedia2** [erdum/php-open-ai-assistant-sdk#1]
Hi,

i have created an assistant on platform.openai.com and tried the following example of your repo:

```
<?php

require(__DIR__ . '/vendor/autoload.php');
# require(__DIR__ . '/php-open-ai-assistant-sdk/src/OpenAIAssistant.php');

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$api_key = "mykey";
$assistant_id = "myassistant_id";

use Erdum\OpenAIAssistant;

$openai = new OpenAIAssistant(
    $api_key,
    $assistant_id
);

$thread_id = isset($_SESSION[$session_id]) ? $_SESSION[$session_id] : null;

if (empty($thread_id)) {
    $thread_id = $openai->create_thread($query);
    $_SESSION[$session_id] = $thread_id;
} else {
    $openai->add_message($thread_id, 'What's the capital of germany?');
}
$openai->run_thread($thread_id);

while ($openai->has_tool_calls) {
    $outputs = $openai->execute_tools(
        $thread_id,
        $openai->tool_call_id
    );
    $openai->submit_tool_outputs(
        $thread_id,
        $openai->tool_call_id,
        $outputs
    );
}

// Get the last recent message
$message = $openai->list_thread_messages($thread_id);
$message = $message[0];
$output = '';

if ($message['role'] == 'assistant') {
    foreach ($message['content'] as $msg) {
        $output .= "{$msg['text']['value']}\n";
    }
    exit($output);
}

```

but I get the following message:

"Fatal error: Uncaught Exception: OpenAI API Returned Unexpected HTTP code 400. { "error": { "message": "Invalid type for 'messages[0].content': expected one of a string or array of objects, but got null instead.", "type": "invalid_request_error", "param": "messages[0].content", "code": "invalid_type" } } in /www/htdocs/[...]/ai/vendor/erdum/php-open-ai-assistant-sdk/src/OpenAIAssistant.php:272 Stack trace: #0 /www/htdocs/[...]/ai/vendor/erdum/php-open-ai-assistant-sdk/src/OpenAIAssistant.php(312): Erdum\OpenAIAssistant->execute_request(Object(CurlHandle)) #1 /www/htdocs/[...]/ai/vendor/erdum/php-open-ai-assistant-sdk/src/OpenAIAssistant.php(78): Erdum\OpenAIAssistant->send_post_request('/threads', Array) #2 /www/htdocs/[...]/ai/assistant.php(23): Erdum\OpenAIAssistant->create_thread(NULL) #3 {main} thrown in /www/htdocs/[...]/ai/vendor/erdum/php-open-ai-assistant-sdk/src/OpenAIAssistant.php on line 272"

What's wrong with my script :-(
Thank you for your support.

Best wishes 
Daniel

**Comment by erdum** [comment]
What I understand, basically it's not an issue. You're doing two wrong things here.

```
if (empty($thread_id)) {
    $thread_id = $openai->create_thread($query);
    $_SESSION[$session_id] = $thread_id;
} else {
    $openai->add_message($thread_id, 'What's the capital of germany?');
}
```

1. From where does the `$query` variable come from?
2. You used wrong quotations here `$openai->add_message($thread_id, 'What's the capital of germany?');` wrap the message string in double quotes or escape the single quote after "What"

I hope this solves your issue.

**Comment by basementmedia2** [comment]
Hi,

thanks for your answer.
The $query comes from your example:

![grafik](https://github.com/erdum/php-open-ai-assistant-sdk/assets/23479553/9e149a51-434e-46d7-9ac2-19e9d6a6b967)

What kind of query do i have to insert here?
Sorry, i am still a beginner :-(

But you are right, it's not an issue, sorry.
Would be great if you could help me in this case anyway to get my "hello ai-world" experience today :-)

**Comment by erdum** [comment]
`$query` is just an initial message to the AI
it could be any text, for example "Hi".

**Comment by basementmedia2** [comment]
Works now, thank you so much!

**Comment by basementmedia2** [comment]
Sorry @erdum one more question.
In general the script works now, means: I get an answer when i ask the assistant.
But the strange thing is: on platforms.openai.com I have switched on the option "file search" and uploaded a custom PDF.
When I ask online the content of the PDF is included in the answer. But when i ask via your API, the Assistant does not know the contents.

How can i activate the option "File search" via your API?

Best wishes and a happy monday :-)

**Comment by erdum** [comment]
@basementmedia2 read [this](https://platform.openai.com/docs/api-reference/assistants/createAssistant) and look at the request body tools array.

Library only offers function tool.

**Comment by basementmedia2** [comment]
OK thank you. Is support of File search planned for future version of library? E.g. also importing of files?
Do you have a "workaround" example how you can use the file search function with PHP anyway?
But It's ok if you don't answer, not really your job here, sorry.
But I'm happy for any support.
